-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  table_name character varying NOT NULL,
  record_id uuid NOT NULL,
  action character varying NOT NULL CHECK (action::text = ANY (ARRAY['INSERT'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying]::text[])),
  old_values jsonb,
  new_values jsonb,
  changed_by uuid,
  changed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id)
);
CREATE TABLE public.claim_customer_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  document_type character varying NOT NULL CHECK (document_type::text = ANY (ARRAY['license'::character varying, 'id'::character varying, 'proof_of_address'::character varying, 'invoice'::character varying, 'police_report'::character varying, 'photos'::character varying, 'other'::character varying]::text[])),
  file_name character varying NOT NULL,
  file_url text NOT NULL,
  file_size integer NOT NULL,
  mime_type character varying,
  upload_date timestamp with time zone DEFAULT now(),
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  notes text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT claim_customer_documents_pkey PRIMARY KEY (id),
  CONSTRAINT claim_customer_documents_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id),
  CONSTRAINT claim_customer_documents_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT claim_customer_documents_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.claim_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  document_type character varying NOT NULL DEFAULT 'evidence'::character varying,
  file_name character varying NOT NULL,
  file_url text NOT NULL,
  file_type character varying NOT NULL,
  file_size integer,
  uploaded_by uuid,
  upload_source character varying DEFAULT 'web'::character varying,
  description text,
  is_verified boolean DEFAULT false,
  verification_notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT claim_documents_pkey PRIMARY KEY (id),
  CONSTRAINT claim_documents_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id),
  CONSTRAINT claim_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.claims (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  claim_number character varying NOT NULL UNIQUE,
  policy_id uuid,
  customer_id uuid,
  adjuster_id uuid,
  incident_date timestamp with time zone NOT NULL,
  claim_type character varying NOT NULL CHECK (claim_type::text = ANY (ARRAY['Colisión'::character varying, 'Robo'::character varying, 'Vandalismo'::character varying, 'Daño por clima'::character varying, 'Daño por granizo'::character varying, 'Incendio'::character varying, 'Otros'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'submitted'::character varying CHECK (status::text = ANY (ARRAY['submitted'::character varying, 'under_review'::character varying, 'pending_documentation'::character varying, 'waiting_approval'::character varying, 'investigating'::character varying, 'approved'::character varying, 'processing_payment'::character varying, 'denied'::character varying, 'closed'::character varying, 'paid'::character varying]::text[])),
  incident_description text NOT NULL,
  incident_location text,
  estimated_damage_cost numeric,
  approved_amount numeric,
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  deductible_amount numeric,
  net_amount numeric,
  approved_by uuid,
  approved_at timestamp with time zone,
  approval_notes text,
  updated_by uuid,
  paid_amount numeric,
  payment_date timestamp with time zone,
  payment_reference character varying,
  police_report_number character varying,
  third_party_involved boolean DEFAULT false,
  injury_involved boolean DEFAULT false,
  fault_percentage integer DEFAULT 100 CHECK (fault_percentage >= 0 AND fault_percentage <= 100),
  agent_id uuid,
  CONSTRAINT claims_pkey PRIMARY KEY (id),
  CONSTRAINT claims_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT claims_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT claims_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.users(id),
  CONSTRAINT claims_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id),
  CONSTRAINT claims_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT claims_adjuster_id_fkey FOREIGN KEY (adjuster_id) REFERENCES public.users(id)
);
CREATE TABLE public.communications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid,
  agent_id uuid,
  policy_id uuid,
  claim_id uuid,
  communication_type character varying NOT NULL CHECK (communication_type::text = ANY (ARRAY['email'::character varying, 'phone'::character varying, 'sms'::character varying, 'chat'::character varying, 'letter'::character varying]::text[])),
  direction character varying NOT NULL CHECK (direction::text = ANY (ARRAY['inbound'::character varying, 'outbound'::character varying]::text[])),
  subject character varying,
  content text NOT NULL,
  status character varying DEFAULT 'sent'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'sent'::character varying, 'delivered'::character varying, 'read'::character varying, 'failed'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT communications_pkey PRIMARY KEY (id),
  CONSTRAINT communications_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT communications_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.users(id),
  CONSTRAINT communications_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id),
  CONSTRAINT communications_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id)
);
CREATE TABLE public.coverage_types (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL UNIQUE,
  description text,
  base_premium numeric NOT NULL,
  is_mandatory boolean DEFAULT false,
  coverage_limit numeric,
  deductible numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT coverage_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  date_of_birth date,
  gender character varying CHECK (gender::text = ANY (ARRAY['M'::character varying, 'F'::character varying, 'Other'::character varying]::text[])),
  address text,
  city character varying,
  state character varying,
  postal_code character varying,
  license_number character varying UNIQUE,
  license_expiry date,
  driving_experience_years integer,
  marital_status character varying CHECK (marital_status::text = ANY (ARRAY['single'::character varying, 'married'::character varying, 'divorced'::character varying, 'widowed'::character varying]::text[])),
  occupation character varying,
  annual_income numeric,
  risk_score integer DEFAULT 50,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  has_accidents boolean DEFAULT false,
  has_claims boolean DEFAULT false,
  country character varying DEFAULT 'Panamá'::character varying,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.damage_assessments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  claim_id uuid,
  adjuster_id uuid,
  damage_description text NOT NULL,
  repair_estimate numeric,
  replacement_estimate numeric,
  recommended_action character varying CHECK (recommended_action::text = ANY (ARRAY['Reparación'::character varying, 'Reemplazo'::character varying, 'Pérdida total'::character varying]::text[])),
  assessment_notes text,
  photos ARRAY,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT damage_assessments_pkey PRIMARY KEY (id),
  CONSTRAINT damage_assessments_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id),
  CONSTRAINT damage_assessments_adjuster_id_fkey FOREIGN KEY (adjuster_id) REFERENCES public.users(id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid,
  policy_id uuid,
  claim_id uuid,
  document_type character varying NOT NULL CHECK (document_type::text = ANY (ARRAY['policy'::character varying, 'claim_form'::character varying, 'photo'::character varying, 'repair_estimate'::character varying, 'police_report'::character varying, 'medical_report'::character varying, 'other'::character varying]::text[])),
  file_name character varying NOT NULL,
  file_path text NOT NULL,
  file_size integer,
  mime_type character varying,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT documents_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id),
  CONSTRAINT documents_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id),
  CONSTRAINT documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.payment_methods (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['credit_card'::character varying::text, 'debit_card'::character varying::text, 'bank_account'::character varying::text, 'digital_wallet'::character varying::text])),
  name character varying NOT NULL,
  last_four character varying NOT NULL,
  expiry_date character varying,
  brand character varying,
  bank_name character varying,
  is_primary boolean DEFAULT false,
  is_active boolean DEFAULT true,
  encrypted_data jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT payment_methods_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  policy_id uuid,
  customer_id uuid,
  claim_id uuid,
  payment_type character varying NOT NULL CHECK (payment_type::text = ANY (ARRAY['premium'::character varying, 'claim'::character varying, 'refund'::character varying, 'fee'::character varying]::text[])),
  amount numeric NOT NULL,
  payment_method character varying CHECK (payment_method::text = ANY (ARRAY['Tarjeta de crédito'::character varying, 'Transferencia bancaria'::character varying, 'Efectivo'::character varying, 'Cheque'::character varying, 'PayPal'::character varying]::text[])),
  payment_status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  payment_date timestamp with time zone,
  due_date date,
  reference_number character varying,
  transaction_id character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id),
  CONSTRAINT payments_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id),
  CONSTRAINT payments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.policies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  policy_number character varying NOT NULL UNIQUE,
  customer_id uuid,
  vehicle_id uuid,
  agent_id uuid,
  policy_type character varying NOT NULL CHECK (policy_type::text = ANY (ARRAY['basica'::character varying, 'limitada'::character varying, 'amplia'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'active'::character varying, 'suspended'::character varying, 'cancelled'::character varying, 'expired'::character varying]::text[])),
  start_date date NOT NULL,
  end_date date NOT NULL,
  premium_amount numeric NOT NULL,
  total_coverage_limit numeric,
  risk_assessment jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  auto_renewal boolean DEFAULT false,
  payment_frequency character varying NOT NULL DEFAULT 'monthly'::character varying CHECK (payment_frequency::text = ANY (ARRAY['monthly'::character varying, 'quarterly'::character varying, 'biannual'::character varying, 'annual'::character varying]::text[])),
  coverage_limit numeric DEFAULT 50000,
  deductible_amount numeric DEFAULT 1000,
  CONSTRAINT policies_pkey PRIMARY KEY (id),
  CONSTRAINT policies_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT policies_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id),
  CONSTRAINT policies_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.users(id)
);
CREATE TABLE public.policy_coverages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  policy_id uuid,
  coverage_type_id uuid,
  coverage_limit numeric,
  deductible numeric,
  premium numeric NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT policy_coverages_pkey PRIMARY KEY (id),
  CONSTRAINT policy_coverages_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id),
  CONSTRAINT policy_coverages_coverage_type_id_fkey FOREIGN KEY (coverage_type_id) REFERENCES public.coverage_types(id)
);
CREATE TABLE public.quotes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  quote_number character varying NOT NULL UNIQUE,
  customer_id uuid,
  vehicle_id uuid,
  agent_id uuid,
  policy_type character varying NOT NULL CHECK (policy_type::text = ANY (ARRAY['basica'::character varying, 'limitada'::character varying, 'amplia'::character varying]::text[])),
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'converted'::character varying]::text[])),
  start_date date NOT NULL,
  end_date date NOT NULL,
  premium_amount numeric NOT NULL,
  payment_frequency character varying NOT NULL DEFAULT 'monthly'::character varying CHECK (payment_frequency::text = ANY (ARRAY['monthly'::character varying, 'quarterly'::character varying, 'biannual'::character varying, 'annual'::character varying]::text[])),
  auto_renewal boolean DEFAULT false,
  selected_coverages jsonb,
  driver_data jsonb,
  vehicle_data jsonb,
  risk_assessment jsonb,
  agent_notes text,
  reviewed_at timestamp with time zone,
  rejected_reason text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  expires_at timestamp with time zone DEFAULT (CURRENT_TIMESTAMP + '30 days'::interval),
  CONSTRAINT quotes_pkey PRIMARY KEY (id),
  CONSTRAINT quotes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT quotes_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id),
  CONSTRAINT quotes_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.users(id)
);
CREATE TABLE public.risk_factors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  category character varying NOT NULL,
  weight numeric NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT risk_factors_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['admin'::character varying, 'agent'::character varying, 'adjuster'::character varying, 'customer'::character varying]::text[])),
  phone character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.vehicles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid,
  make character varying NOT NULL,
  model character varying NOT NULL,
  year integer NOT NULL,
  vin character varying UNIQUE,
  license_plate character varying UNIQUE,
  color character varying,
  engine_size character varying,
  fuel_type character varying CHECK (fuel_type::text = ANY (ARRAY['Gasolina'::character varying, 'Diesel'::character varying, 'Híbrido'::character varying, 'Eléctrico'::character varying, 'GLP'::character varying]::text[])),
  transmission character varying CHECK (transmission::text = ANY (ARRAY['Manual'::character varying, 'Automático'::character varying, 'CVT'::character varying]::text[])),
  vehicle_type character varying CHECK (vehicle_type::text = ANY (ARRAY['Sedán'::character varying, 'SUV'::character varying, 'Hatchback'::character varying, 'Pickup'::character varying, 'Convertible'::character varying, 'Coupé'::character varying, 'Wagon'::character varying]::text[])),
  estimated_value numeric,
  mileage integer,
  safety_features ARRAY,
  anti_theft_devices ARRAY,
  garage_type character varying CHECK (garage_type::text = ANY (ARRAY['enclosed'::character varying, 'covered'::character varying, 'street'::character varying]::text[])),
  annual_mileage integer,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  usage_type character varying CHECK (usage_type::text = ANY (ARRAY['personal'::character varying, 'commercial'::character varying, 'taxi'::character varying, 'delivery'::character varying, 'other'::character varying]::text[])),
  CONSTRAINT vehicles_pkey PRIMARY KEY (id),
  CONSTRAINT vehicles_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);